### ISSUE TITLE
Custom wrapper not working on 2.2.1

### ISSUE THREAD

**Issue by abgrac** [vinitkumar/json2xml#36]
I can't seem to make the custom Json2xml(data, WRAPPER, INDENT) to work. Keeps returning "unexpected keyword argument 'wrapper'".
Also did not found any implementation of it on the json2xml.py src code.

 - OS: Windows 7 x64

**Comment by vinitkumar** [comment]
Any updates? @abgrac

**Comment by angelo-di-marzio** [comment]
Hello, I have the same issue. TypeError: __init__() got an unexpected keyword argument 'wrapper'
I can't manage to make it work. I've followed your instructions on [use wrapper and indent](https://github.com/vinitkumar/json2xml#custom-wrapper-and-indent-size)
I'm on json2xml version 2.2.1
I'm here if you need more informations

**Comment by vinitkumar** [comment]
@angelo-di-marzio Could you please share these things:

- Python Version
- Full crash log?
- How can I reproduce the bug? Share the code that you used?
- Did you install the json2xml from `pip` or did you clone the repo?

**Comment by vinitkumar** [comment]
@angelo-di-marzio Alright, I am able to reproduce the bug now.

**Comment by angelo-di-marzio** [comment]
I installed it from pip. I'm using Python 3.7.
The full log is "TypeError: __init__() got an unexpected keyword argument 'wrapper'"

`annotation_list = version["annotation_list"]
        data = Json2xml.fromstring(json.dumps(annotation_list)).data
        data_object = Json2xml(data, wrapper="custom", indent=4)
        annotations_xml=data_object.json2xml()
        file = open(path, "w+")
        file.write(annotations_xml)
        file.close()
        return file`

**Comment by vinitkumar** [comment]
Hi @abgrac & @angelo-di-marzio 

Thanks for reporting this bug. The bug wasn't in the code but in the pypi released code that was outdated and didn't had the `wrapper` in the constructor.

Well, I have a good news. I did a major refactor & cleaned up the code. This is also a breaking change and you will need to update the code sample using this library. Please look at the readme https://github.com/vinitkumar/json2xml#usage or at the docs
https://json2xml.readthedocs.io/ 

If you follow the readme/docs, everything should just work.

In order to upgrade run this:

```
pip install --upgrade json2xml
```

Or to install the latest version

```
pip install json2xml==3.0.0
```

**Comment by vinitkumar** [comment]
@abgrac @angelo-di-marzio Closing this as the issue is fixed. Please update the plugin and follow the docs and it should just work for you.
